import { createElement } from 'lwc';
import Day26GettingrecordIdAndObjectApiname from 'c/day26GettingrecordIdAndObjectApiname';

describe('c-day26-gettingrecord-id-and-object-apiname', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-day26-gettingrecord-id-and-object-apiname', {
            is: Day26GettingrecordIdAndObjectApiname
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});